### PR TITLE
Project structure, style, and others

### PR DESCRIPTION
**Pull request by cmaureir**
Hello,

I went through the code and made some changes.
Feel free to accept or reject the changes.

As a general comment, maybe you can check your code styling with any tool, `flake8`, `black` or any other, to at least approach the code to PEP8 standards.

Cheers!

### CODE REVIEW

**Review by Aens — APPROVED** [review]

**Review by Aens — APPROVED** [review]

**Review by Aens — COMMENTED** [review]
So far I'm more confident with my own style, I hate to see in 3 lines what can be easily explained in 1 (as example: a List with just 2 elements, like all my change_statusbar lines). I also use a 100 characters limit instead of 80 because I feel 80 isn't enough for most stuff.

**Comment by cmaureir** [comment]
> So far I'm more confident with my own style, I hate to see in 3 lines what can be easily explained in 1 (as example: a List with just 2 elements, like all my change_statusbar lines). I also use a 100 characters limit instead of 80 because I feel 80 isn't enough for most stuff.

Sure, I totally agree with your decisions. Keep in mind the [PEP8](https://www.python.org/dev/peps/pep-0008/) styling though.

I have been in projects where you sacrifice a couple of guidelines, like line length, so it's totally valid ;)

**Review by Aens — APPROVED** [review]

**Comment by Aens** [comment]
I am merging everything except black coding (If I find how to. I'm a first timer in Github yay!). Thank you for the suggestions.

**Comment by cmaureir** [comment]
You can also use [flake8](http://flake8.pycqa.org/en/latest/) to just "see" which styling issues are in your code (that will not modify your code)

**Comment by Aens** [comment]
Yeah I will probably do that. As I totally broke this merge request because I wasn't aware of how github works and I did several changes I'm going to close it here. Everything should, however, be already merged except the style code (did manually changed everything else). Is that Okay?

**Comment by cmaureir** [comment]
I think so, as long as the application is working  I don't see any problem.

**Pull request closed without merging**
